/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpcomingIndexRouteImport } from './routes/upcoming/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as NewlyReleasedIndexRouteImport } from './routes/newly-released/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as AllGamesIndexRouteImport } from './routes/all-games/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as SettingsSettingsRouteImport } from './routes/settings/_settings'
import { Route as GamesGamesSlugRouteImport } from './routes/games/$gamesSlug'
import { Route as SettingsSettingsIndexRouteImport } from './routes/settings/_settings.index'
import { Route as UUsernameProfileRouteImport } from './routes/u/$username/_profile'
import { Route as SettingsSettingsAccountRouteImport } from './routes/settings/_settings.account'
import { Route as UUsernameProfileIndexRouteImport } from './routes/u/$username/_profile.index'
import { Route as UUsernameListListRouteImport } from './routes/u/$username/list/_list'
import { Route as UUsernameProfileReviewsRouteImport } from './routes/u/$username/_profile.reviews'
import { Route as UUsernameProfileListsRouteImport } from './routes/u/$username/_profile.lists'
import { Route as UUsernameProfileGamesRouteImport } from './routes/u/$username/_profile.games'
import { Route as UUsernameProfileActivityRouteImport } from './routes/u/$username/_profile.activity'
import { Route as UUsernameListListListslugRouteImport } from './routes/u/$username/list/_list.$listslug'
import { Route as UUsernameProfileLikesLikesRouteImport } from './routes/u/$username/_profile.likes/_likes'
import { Route as UUsernameProfileLikesLikesIndexRouteImport } from './routes/u/$username/_profile.likes/_likes.index'
import { Route as UUsernameProfileLikesLikesReviewsRouteImport } from './routes/u/$username/_profile.likes/_likes.reviews'
import { Route as UUsernameProfileLikesLikesListsRouteImport } from './routes/u/$username/_profile.likes/_likes.lists'
import { Route as UUsernameProfileLikesLikesGamesRouteImport } from './routes/u/$username/_profile.likes/_likes.games'

const SettingsRouteImport = createFileRoute('/settings')()
const UUsernameListRouteImport = createFileRoute('/u/$username/list')()
const UUsernameProfileLikesRouteImport = createFileRoute(
  '/u/$username/_profile/likes',
)()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingIndexRoute = UpcomingIndexRouteImport.update({
  id: '/upcoming/',
  path: '/upcoming/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewlyReleasedIndexRoute = NewlyReleasedIndexRouteImport.update({
  id: '/newly-released/',
  path: '/newly-released/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllGamesIndexRoute = AllGamesIndexRouteImport.update({
  id: '/all-games/',
  path: '/all-games/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSettingsRoute = SettingsSettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => SettingsRoute,
} as any)
const GamesGamesSlugRoute = GamesGamesSlugRouteImport.update({
  id: '/games/$gamesSlug',
  path: '/games/$gamesSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameListRoute = UUsernameListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => UUsernameRoute,
} as any)
const SettingsSettingsIndexRoute = SettingsSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const UUsernameProfileRoute = UUsernameProfileRouteImport.update({
  id: '/_profile',
  getParentRoute: () => UUsernameRoute,
} as any)
const SettingsSettingsAccountRoute = SettingsSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const UUsernameProfileLikesRoute = UUsernameProfileLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => UUsernameProfileRoute,
} as any)
const UUsernameProfileIndexRoute = UUsernameProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameProfileRoute,
} as any)
const UUsernameListListRoute = UUsernameListListRouteImport.update({
  id: '/_list',
  getParentRoute: () => UUsernameListRoute,
} as any)
const UUsernameProfileReviewsRoute = UUsernameProfileReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UUsernameProfileRoute,
} as any)
const UUsernameProfileListsRoute = UUsernameProfileListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => UUsernameProfileRoute,
} as any)
const UUsernameProfileGamesRoute = UUsernameProfileGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => UUsernameProfileRoute,
} as any)
const UUsernameProfileActivityRoute =
  UUsernameProfileActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => UUsernameProfileRoute,
  } as any)
const UUsernameListListListslugRoute =
  UUsernameListListListslugRouteImport.update({
    id: '/$listslug',
    path: '/$listslug',
    getParentRoute: () => UUsernameListListRoute,
  } as any)
const UUsernameProfileLikesLikesRoute =
  UUsernameProfileLikesLikesRouteImport.update({
    id: '/_likes',
    getParentRoute: () => UUsernameProfileLikesRoute,
  } as any)
const UUsernameProfileLikesLikesIndexRoute =
  UUsernameProfileLikesLikesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UUsernameProfileLikesLikesRoute,
  } as any)
const UUsernameProfileLikesLikesReviewsRoute =
  UUsernameProfileLikesLikesReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => UUsernameProfileLikesLikesRoute,
  } as any)
const UUsernameProfileLikesLikesListsRoute =
  UUsernameProfileLikesLikesListsRouteImport.update({
    id: '/lists',
    path: '/lists',
    getParentRoute: () => UUsernameProfileLikesLikesRoute,
  } as any)
const UUsernameProfileLikesLikesGamesRoute =
  UUsernameProfileLikesLikesGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => UUsernameProfileLikesLikesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$gamesSlug': typeof GamesGamesSlugRoute
  '/settings': typeof SettingsSettingsRouteWithChildren
  '/u/$username': typeof UUsernameProfileRouteWithChildren
  '/all-games': typeof AllGamesIndexRoute
  '/games': typeof GamesIndexRoute
  '/login': typeof LoginIndexRoute
  '/newly-released': typeof NewlyReleasedIndexRoute
  '/search': typeof SearchIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/upcoming': typeof UpcomingIndexRoute
  '/settings/account': typeof SettingsSettingsAccountRoute
  '/settings/': typeof SettingsSettingsIndexRoute
  '/u/$username/activity': typeof UUsernameProfileActivityRoute
  '/u/$username/games': typeof UUsernameProfileGamesRoute
  '/u/$username/lists': typeof UUsernameProfileListsRoute
  '/u/$username/reviews': typeof UUsernameProfileReviewsRoute
  '/u/$username/list': typeof UUsernameListListRouteWithChildren
  '/u/$username/': typeof UUsernameProfileIndexRoute
  '/u/$username/likes': typeof UUsernameProfileLikesLikesRouteWithChildren
  '/u/$username/list/$listslug': typeof UUsernameListListListslugRoute
  '/u/$username/likes/games': typeof UUsernameProfileLikesLikesGamesRoute
  '/u/$username/likes/lists': typeof UUsernameProfileLikesLikesListsRoute
  '/u/$username/likes/reviews': typeof UUsernameProfileLikesLikesReviewsRoute
  '/u/$username/likes/': typeof UUsernameProfileLikesLikesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$gamesSlug': typeof GamesGamesSlugRoute
  '/settings': typeof SettingsSettingsIndexRoute
  '/u/$username': typeof UUsernameProfileIndexRoute
  '/all-games': typeof AllGamesIndexRoute
  '/games': typeof GamesIndexRoute
  '/login': typeof LoginIndexRoute
  '/newly-released': typeof NewlyReleasedIndexRoute
  '/search': typeof SearchIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/upcoming': typeof UpcomingIndexRoute
  '/settings/account': typeof SettingsSettingsAccountRoute
  '/u/$username/activity': typeof UUsernameProfileActivityRoute
  '/u/$username/games': typeof UUsernameProfileGamesRoute
  '/u/$username/lists': typeof UUsernameProfileListsRoute
  '/u/$username/reviews': typeof UUsernameProfileReviewsRoute
  '/u/$username/list': typeof UUsernameListListRouteWithChildren
  '/u/$username/likes': typeof UUsernameProfileLikesLikesIndexRoute
  '/u/$username/list/$listslug': typeof UUsernameListListListslugRoute
  '/u/$username/likes/games': typeof UUsernameProfileLikesLikesGamesRoute
  '/u/$username/likes/lists': typeof UUsernameProfileLikesLikesListsRoute
  '/u/$username/likes/reviews': typeof UUsernameProfileLikesLikesReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$gamesSlug': typeof GamesGamesSlugRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/_settings': typeof SettingsSettingsRouteWithChildren
  '/u/$username': typeof UUsernameRouteWithChildren
  '/all-games/': typeof AllGamesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/newly-released/': typeof NewlyReleasedIndexRoute
  '/search/': typeof SearchIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/upcoming/': typeof UpcomingIndexRoute
  '/settings/_settings/account': typeof SettingsSettingsAccountRoute
  '/u/$username/_profile': typeof UUsernameProfileRouteWithChildren
  '/settings/_settings/': typeof SettingsSettingsIndexRoute
  '/u/$username/_profile/activity': typeof UUsernameProfileActivityRoute
  '/u/$username/_profile/games': typeof UUsernameProfileGamesRoute
  '/u/$username/_profile/lists': typeof UUsernameProfileListsRoute
  '/u/$username/_profile/reviews': typeof UUsernameProfileReviewsRoute
  '/u/$username/list': typeof UUsernameListRouteWithChildren
  '/u/$username/list/_list': typeof UUsernameListListRouteWithChildren
  '/u/$username/_profile/': typeof UUsernameProfileIndexRoute
  '/u/$username/_profile/likes': typeof UUsernameProfileLikesRouteWithChildren
  '/u/$username/_profile/likes/_likes': typeof UUsernameProfileLikesLikesRouteWithChildren
  '/u/$username/list/_list/$listslug': typeof UUsernameListListListslugRoute
  '/u/$username/_profile/likes/_likes/games': typeof UUsernameProfileLikesLikesGamesRoute
  '/u/$username/_profile/likes/_likes/lists': typeof UUsernameProfileLikesLikesListsRoute
  '/u/$username/_profile/likes/_likes/reviews': typeof UUsernameProfileLikesLikesReviewsRoute
  '/u/$username/_profile/likes/_likes/': typeof UUsernameProfileLikesLikesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$gamesSlug'
    | '/settings'
    | '/u/$username'
    | '/all-games'
    | '/games'
    | '/login'
    | '/newly-released'
    | '/search'
    | '/sign-up'
    | '/upcoming'
    | '/settings/account'
    | '/settings/'
    | '/u/$username/activity'
    | '/u/$username/games'
    | '/u/$username/lists'
    | '/u/$username/reviews'
    | '/u/$username/list'
    | '/u/$username/'
    | '/u/$username/likes'
    | '/u/$username/list/$listslug'
    | '/u/$username/likes/games'
    | '/u/$username/likes/lists'
    | '/u/$username/likes/reviews'
    | '/u/$username/likes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$gamesSlug'
    | '/settings'
    | '/u/$username'
    | '/all-games'
    | '/games'
    | '/login'
    | '/newly-released'
    | '/search'
    | '/sign-up'
    | '/upcoming'
    | '/settings/account'
    | '/u/$username/activity'
    | '/u/$username/games'
    | '/u/$username/lists'
    | '/u/$username/reviews'
    | '/u/$username/list'
    | '/u/$username/likes'
    | '/u/$username/list/$listslug'
    | '/u/$username/likes/games'
    | '/u/$username/likes/lists'
    | '/u/$username/likes/reviews'
  id:
    | '__root__'
    | '/'
    | '/games/$gamesSlug'
    | '/settings'
    | '/settings/_settings'
    | '/u/$username'
    | '/all-games/'
    | '/games/'
    | '/login/'
    | '/newly-released/'
    | '/search/'
    | '/sign-up/'
    | '/upcoming/'
    | '/settings/_settings/account'
    | '/u/$username/_profile'
    | '/settings/_settings/'
    | '/u/$username/_profile/activity'
    | '/u/$username/_profile/games'
    | '/u/$username/_profile/lists'
    | '/u/$username/_profile/reviews'
    | '/u/$username/list'
    | '/u/$username/list/_list'
    | '/u/$username/_profile/'
    | '/u/$username/_profile/likes'
    | '/u/$username/_profile/likes/_likes'
    | '/u/$username/list/_list/$listslug'
    | '/u/$username/_profile/likes/_likes/games'
    | '/u/$username/_profile/likes/_likes/lists'
    | '/u/$username/_profile/likes/_likes/reviews'
    | '/u/$username/_profile/likes/_likes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesGamesSlugRoute: typeof GamesGamesSlugRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UUsernameRoute: typeof UUsernameRouteWithChildren
  AllGamesIndexRoute: typeof AllGamesIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  NewlyReleasedIndexRoute: typeof NewlyReleasedIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  UpcomingIndexRoute: typeof UpcomingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming/': {
      id: '/upcoming/'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newly-released/': {
      id: '/newly-released/'
      path: '/newly-released'
      fullPath: '/newly-released'
      preLoaderRoute: typeof NewlyReleasedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-games/': {
      id: '/all-games/'
      path: '/all-games'
      fullPath: '/all-games'
      preLoaderRoute: typeof AllGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_settings': {
      id: '/settings/_settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsSettingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/games/$gamesSlug': {
      id: '/games/$gamesSlug'
      path: '/games/$gamesSlug'
      fullPath: '/games/$gamesSlug'
      preLoaderRoute: typeof GamesGamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/list': {
      id: '/u/$username/list'
      path: '/list'
      fullPath: '/u/$username/list'
      preLoaderRoute: typeof UUsernameListRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/settings/_settings/': {
      id: '/settings/_settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsSettingsIndexRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/u/$username/_profile': {
      id: '/u/$username/_profile'
      path: ''
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameProfileRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/settings/_settings/account': {
      id: '/settings/_settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsSettingsAccountRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/u/$username/_profile/likes': {
      id: '/u/$username/_profile/likes'
      path: '/likes'
      fullPath: '/u/$username/likes'
      preLoaderRoute: typeof UUsernameProfileLikesRouteImport
      parentRoute: typeof UUsernameProfileRoute
    }
    '/u/$username/_profile/': {
      id: '/u/$username/_profile/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameProfileIndexRouteImport
      parentRoute: typeof UUsernameProfileRoute
    }
    '/u/$username/list/_list': {
      id: '/u/$username/list/_list'
      path: '/list'
      fullPath: '/u/$username/list'
      preLoaderRoute: typeof UUsernameListListRouteImport
      parentRoute: typeof UUsernameListRoute
    }
    '/u/$username/_profile/reviews': {
      id: '/u/$username/_profile/reviews'
      path: '/reviews'
      fullPath: '/u/$username/reviews'
      preLoaderRoute: typeof UUsernameProfileReviewsRouteImport
      parentRoute: typeof UUsernameProfileRoute
    }
    '/u/$username/_profile/lists': {
      id: '/u/$username/_profile/lists'
      path: '/lists'
      fullPath: '/u/$username/lists'
      preLoaderRoute: typeof UUsernameProfileListsRouteImport
      parentRoute: typeof UUsernameProfileRoute
    }
    '/u/$username/_profile/games': {
      id: '/u/$username/_profile/games'
      path: '/games'
      fullPath: '/u/$username/games'
      preLoaderRoute: typeof UUsernameProfileGamesRouteImport
      parentRoute: typeof UUsernameProfileRoute
    }
    '/u/$username/_profile/activity': {
      id: '/u/$username/_profile/activity'
      path: '/activity'
      fullPath: '/u/$username/activity'
      preLoaderRoute: typeof UUsernameProfileActivityRouteImport
      parentRoute: typeof UUsernameProfileRoute
    }
    '/u/$username/list/_list/$listslug': {
      id: '/u/$username/list/_list/$listslug'
      path: '/$listslug'
      fullPath: '/u/$username/list/$listslug'
      preLoaderRoute: typeof UUsernameListListListslugRouteImport
      parentRoute: typeof UUsernameListListRoute
    }
    '/u/$username/_profile/likes/_likes': {
      id: '/u/$username/_profile/likes/_likes'
      path: '/likes'
      fullPath: '/u/$username/likes'
      preLoaderRoute: typeof UUsernameProfileLikesLikesRouteImport
      parentRoute: typeof UUsernameProfileLikesRoute
    }
    '/u/$username/_profile/likes/_likes/': {
      id: '/u/$username/_profile/likes/_likes/'
      path: '/'
      fullPath: '/u/$username/likes/'
      preLoaderRoute: typeof UUsernameProfileLikesLikesIndexRouteImport
      parentRoute: typeof UUsernameProfileLikesLikesRoute
    }
    '/u/$username/_profile/likes/_likes/reviews': {
      id: '/u/$username/_profile/likes/_likes/reviews'
      path: '/reviews'
      fullPath: '/u/$username/likes/reviews'
      preLoaderRoute: typeof UUsernameProfileLikesLikesReviewsRouteImport
      parentRoute: typeof UUsernameProfileLikesLikesRoute
    }
    '/u/$username/_profile/likes/_likes/lists': {
      id: '/u/$username/_profile/likes/_likes/lists'
      path: '/lists'
      fullPath: '/u/$username/likes/lists'
      preLoaderRoute: typeof UUsernameProfileLikesLikesListsRouteImport
      parentRoute: typeof UUsernameProfileLikesLikesRoute
    }
    '/u/$username/_profile/likes/_likes/games': {
      id: '/u/$username/_profile/likes/_likes/games'
      path: '/games'
      fullPath: '/u/$username/likes/games'
      preLoaderRoute: typeof UUsernameProfileLikesLikesGamesRouteImport
      parentRoute: typeof UUsernameProfileLikesLikesRoute
    }
  }
}

interface SettingsSettingsRouteChildren {
  SettingsSettingsAccountRoute: typeof SettingsSettingsAccountRoute
  SettingsSettingsIndexRoute: typeof SettingsSettingsIndexRoute
}

const SettingsSettingsRouteChildren: SettingsSettingsRouteChildren = {
  SettingsSettingsAccountRoute: SettingsSettingsAccountRoute,
  SettingsSettingsIndexRoute: SettingsSettingsIndexRoute,
}

const SettingsSettingsRouteWithChildren =
  SettingsSettingsRoute._addFileChildren(SettingsSettingsRouteChildren)

interface SettingsRouteChildren {
  SettingsSettingsRoute: typeof SettingsSettingsRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsRoute: SettingsSettingsRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface UUsernameProfileLikesLikesRouteChildren {
  UUsernameProfileLikesLikesGamesRoute: typeof UUsernameProfileLikesLikesGamesRoute
  UUsernameProfileLikesLikesListsRoute: typeof UUsernameProfileLikesLikesListsRoute
  UUsernameProfileLikesLikesReviewsRoute: typeof UUsernameProfileLikesLikesReviewsRoute
  UUsernameProfileLikesLikesIndexRoute: typeof UUsernameProfileLikesLikesIndexRoute
}

const UUsernameProfileLikesLikesRouteChildren: UUsernameProfileLikesLikesRouteChildren =
  {
    UUsernameProfileLikesLikesGamesRoute: UUsernameProfileLikesLikesGamesRoute,
    UUsernameProfileLikesLikesListsRoute: UUsernameProfileLikesLikesListsRoute,
    UUsernameProfileLikesLikesReviewsRoute:
      UUsernameProfileLikesLikesReviewsRoute,
    UUsernameProfileLikesLikesIndexRoute: UUsernameProfileLikesLikesIndexRoute,
  }

const UUsernameProfileLikesLikesRouteWithChildren =
  UUsernameProfileLikesLikesRoute._addFileChildren(
    UUsernameProfileLikesLikesRouteChildren,
  )

interface UUsernameProfileLikesRouteChildren {
  UUsernameProfileLikesLikesRoute: typeof UUsernameProfileLikesLikesRouteWithChildren
}

const UUsernameProfileLikesRouteChildren: UUsernameProfileLikesRouteChildren = {
  UUsernameProfileLikesLikesRoute: UUsernameProfileLikesLikesRouteWithChildren,
}

const UUsernameProfileLikesRouteWithChildren =
  UUsernameProfileLikesRoute._addFileChildren(
    UUsernameProfileLikesRouteChildren,
  )

interface UUsernameProfileRouteChildren {
  UUsernameProfileActivityRoute: typeof UUsernameProfileActivityRoute
  UUsernameProfileGamesRoute: typeof UUsernameProfileGamesRoute
  UUsernameProfileListsRoute: typeof UUsernameProfileListsRoute
  UUsernameProfileReviewsRoute: typeof UUsernameProfileReviewsRoute
  UUsernameProfileIndexRoute: typeof UUsernameProfileIndexRoute
  UUsernameProfileLikesRoute: typeof UUsernameProfileLikesRouteWithChildren
}

const UUsernameProfileRouteChildren: UUsernameProfileRouteChildren = {
  UUsernameProfileActivityRoute: UUsernameProfileActivityRoute,
  UUsernameProfileGamesRoute: UUsernameProfileGamesRoute,
  UUsernameProfileListsRoute: UUsernameProfileListsRoute,
  UUsernameProfileReviewsRoute: UUsernameProfileReviewsRoute,
  UUsernameProfileIndexRoute: UUsernameProfileIndexRoute,
  UUsernameProfileLikesRoute: UUsernameProfileLikesRouteWithChildren,
}

const UUsernameProfileRouteWithChildren =
  UUsernameProfileRoute._addFileChildren(UUsernameProfileRouteChildren)

interface UUsernameListListRouteChildren {
  UUsernameListListListslugRoute: typeof UUsernameListListListslugRoute
}

const UUsernameListListRouteChildren: UUsernameListListRouteChildren = {
  UUsernameListListListslugRoute: UUsernameListListListslugRoute,
}

const UUsernameListListRouteWithChildren =
  UUsernameListListRoute._addFileChildren(UUsernameListListRouteChildren)

interface UUsernameListRouteChildren {
  UUsernameListListRoute: typeof UUsernameListListRouteWithChildren
}

const UUsernameListRouteChildren: UUsernameListRouteChildren = {
  UUsernameListListRoute: UUsernameListListRouteWithChildren,
}

const UUsernameListRouteWithChildren = UUsernameListRoute._addFileChildren(
  UUsernameListRouteChildren,
)

interface UUsernameRouteChildren {
  UUsernameProfileRoute: typeof UUsernameProfileRouteWithChildren
  UUsernameListRoute: typeof UUsernameListRouteWithChildren
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameProfileRoute: UUsernameProfileRouteWithChildren,
  UUsernameListRoute: UUsernameListRouteWithChildren,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGamesSlugRoute: GamesGamesSlugRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UUsernameRoute: UUsernameRouteWithChildren,
  AllGamesIndexRoute: AllGamesIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  NewlyReleasedIndexRoute: NewlyReleasedIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  UpcomingIndexRoute: UpcomingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
